version: "3"

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - PORT=3000

  database:
    build:
      context: ./database
    ports:
      - "8090:8090"
    volumes:
      - ./database/pb_data:/pb/pb_data

  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
